import type { Car } from "@/types/car";

export const cars: Car[] = [
  {
    id: "bmw-3-f30",
    brand: "BMW",
    model: "3 Series F30",
    year: 2012,
    class: "comfort",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 4500,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80",
    available: true,
    popular: true,
    extra: "Аудиосистема, подогрев сидений",

    generation: "F30/F31 (2011—2015)",
    drive: "rear",
    modification: "320i 2.0 AT (184 л.с.)",
    steering: "left",
    trim: "SE",
    extras: ["Аудиосистема", "Сиденья с подогревом", "Круиз-контроль", "Парктроник"],
    rentalType: "self",
    minAge: 23,
    minExperience: 3,
    deposit: "Нет",
    insurance: "ОСАГО",
    minDays: 1,
    mileageLimit: "Нет",
    idealFor: [
      "Городских приключений — компактные габариты и маневренность для лёгкой парковки.",
      "Загородных поездок — динамичный разгон и устойчивость на трассе.",
      "Фотосессий — синий BMW на фоне пейзажей станет ярким кадром вашего отпуска!",
    ],
    priceTiers: [
      { label: "1-3 суток", price: 4500 },
      { label: "4-7 суток", price: 4200 },
      { label: "от 8 суток", price: 3900 },
    ],
  },

  // ===== Эконом =====
  {
    id: "kia-rio",
    brand: "Kia",
    model: "Rio",
    year: 2022,
    class: "economy",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 2,
    pricePerDay: 2200,
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&q=80",
    available: true,
    popular: true,
  },
  {
    id: "hyundai-solaris",
    brand: "Hyundai",
    model: "Solaris",
    year: 2023,
    class: "economy",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 2,
    pricePerDay: 2300,
    image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&q=80",
    available: true,
  },
  {
    id: "honda-civic",
    brand: "Honda",
    model: "Civic",
    year: 2021,
    class: "economy",
    bodyType: "hatchback",
    transmission: "variator",
    fuel: "petrol",
    seats: 5,
    doors: 5,
    baggage: 2,
    pricePerDay: 2800,
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&q=80",
    available: true,
  },

  // ===== Комфорт =====
  {
    id: "kia-k5",
    brand: "Kia",
    model: "K5",
    year: 2022,
    class: "comfort",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 3800,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=80",
    available: true,
    popular: true,
  },
  {
    id: "nissan-teana",
    brand: "Nissan",
    model: "Teana",
    year: 2020,
    class: "comfort",
    bodyType: "sedan",
    transmission: "variator",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 4200,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=80",
    available: true,
    popular: true,
  },
  {
    id: "citroen-c5",
    brand: "Citroen",
    model: "C5 Aircross",
    year: 2021,
    class: "comfort",
    bodyType: "suv",
    transmission: "automatic",
    fuel: "diesel",
    seats: 5,
    doors: 5,
    baggage: 4,
    pricePerDay: 3900,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
    available: true,
  },

  // ===== Бизнес =====
  {
    id: "toyota-camry",
    brand: "Toyota",
    model: "Camry",
    year: 2023,
    class: "business",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 5500,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=80",
    available: true,
    popular: true,
  },
  {
    id: "audi-a3",
    brand: "Audi",
    model: "A3",
    year: 2022,
    class: "business",
    bodyType: "sedan",
    transmission: "robot",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 4200,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
    available: true,
    popular: true,
  },
  {
    id: "bmw-5",
    brand: "BMW",
    model: "5 Series",
    year: 2023,
    class: "business",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 9500,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80",
    available: true,
  },

  // ===== Премиум =====
  {
    id: "mercedes-e",
    brand: "Mercedes",
    model: "E-Class",
    year: 2023,
    class: "premium",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 10500,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80",
    available: true,
  },
  {
    id: "mercedes-s",
    brand: "Mercedes",
    model: "S-Class",
    year: 2024,
    class: "premium",
    bodyType: "sedan",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 4,
    baggage: 3,
    pricePerDay: 14000,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80",
    available: true,
  },
  {
    id: "lexus-lx",
    brand: "Lexus",
    model: "LX 600",
    year: 2023,
    class: "premium",
    bodyType: "suv",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 5,
    baggage: 5,
    pricePerDay: 18000,
    image: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=1200&q=80",
    available: true,
  },
  {
    id: "porsche-macan",
    brand: "Porsche",
    model: "Macan",
    year: 2023,
    class: "premium",
    bodyType: "suv",
    transmission: "robot",
    fuel: "petrol",
    seats: 5,
    doors: 5,
    baggage: 4,
    pricePerDay: 15000,
    image: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=1200&q=80",
    available: true,
    popular: true,
  },

  // ===== SUV =====
  {
    id: "hyundai-tucson",
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    class: "suv",
    bodyType: "suv",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 5,
    baggage: 4,
    pricePerDay: 5600,
    image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&q=80",
    available: true,
  },
  {
    id: "kia-sportage",
    brand: "Kia",
    model: "Sportage",
    year: 2022,
    class: "suv",
    bodyType: "suv",
    transmission: "automatic",
    fuel: "petrol",
    seats: 5,
    doors: 5,
    baggage: 4,
    pricePerDay: 5900,
    image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&q=80",
    available: true,
  },

  // ===== Кабриолет =====
  {
    id: "mini-cabrio",
    brand: "MINI",
    model: "Cooper Cabrio",
    year: 2022,
    class: "premium",
    bodyType: "cabriolet",
    transmission: "automatic",
    fuel: "petrol",
    seats: 4,
    doors: 2,
    baggage: 1,
    pricePerDay: 8900,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80",
    available: true,
  },

  // ===== Минивэн =====
  {
    id: "kia-carnival",
    brand: "Kia",
    model: "Carnival",
    year: 2023,
    class: "minivan",
    bodyType: "minivan",
    transmission: "automatic",
    fuel: "diesel",
    seats: 7,
    doors: 5,
    baggage: 6,
    pricePerDay: 7500,
    image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&q=80",
    available: true,
  },
  {
    id: "kaiyi-x3",
    brand: "Kaiyi",
    model: "X3",
    year: 2024,
    class: "comfort",
    bodyType: "suv",
    transmission: "variator",
    fuel: "petrol",
    seats: 5,
    doors: 5,
    baggage: 3,
    pricePerDay: 3500,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
    available: true,
  },
];

export const brands = Array.from(new Set(cars.map((c) => c.brand))).sort();

const prices = cars.map((c) => c.pricePerDay).filter((n) => Number.isFinite(n));
const years = cars.map((c) => c.year).filter((n) => Number.isFinite(n));

export const priceBounds = {
  min: prices.length ? Math.min(...prices) : 0,
  max: prices.length ? Math.max(...prices) : 20000,
};

export const yearBounds = {
  min: years.length ? Math.min(...years) : 2000,
  max: years.length ? Math.max(...years) : new Date().getFullYear(),
};